### ISSUE TITLE
Differences between v3 and v4

### ISSUE THREAD

**Issue by DLopezGo90** [vlkv/avalanche#12]
The only differences are the microcontroller and OLED position? the layout for keys has not been changed? 

Thanks in advance

**Comment by vlkv** [comment]
Hi))) https://github.com/vlkv/avalanche/blob/master/release_notes.md#v4

**Comment by DLopezGo90** [comment]
No more RGB underglow support? (backlight) 

Not even LEDs strip?

**Comment by vlkv** [comment]
> Not even LEDs strip?
Well, at least not yet. Pads for LEDs strip could be added I guess, have no word against this idea)

**Comment by DLopezGo90** [comment]
> Well, at least not yet. Pads for LEDs strip could be added I guess, have no word against this idea)

I think it was a mistake to remove the underglow leds. Avalanche competitors (corne, sofle rgb, kyria, etc) have underglow leds. If FR4 or acrylic plates are used to build an avalanche the lack of underglow leds will be evident
