### ISSUE TITLE
v4.2 JLCPCB Order

### ISSUE THREAD

**Issue by winder** [vlkv/avalanche#13]
I'm ordering some v4.2 PCBs and JLCPCB sent the following question. From the image it looks like the holes are green, does this mean the hotswap sockets and spring housing hole are missing?
```
As shown below, it seems this is a working gerber ready for production, is that right?

Shall we fabricate as per this gerber without further compensation and optimization?
```

![image](https://user-images.githubusercontent.com/125509/149954019-ecd8cfef-ce81-429c-b59a-0eadfb685d4e.png)

**Comment by vlkv** [comment]
`As shown below, it seems this is a working gerber ready for production, is that right?`
Yes
`Shall we fabricate as per this gerber without further compensation and optimization?` 
Ask them, what do they mean by `compensation and optimization`?

` From the image it looks like the holes are green, does this mean the hotswap sockets and spring housing hole are missing?`
Have no idea what that could mean.

**Comment by winder** [comment]
This looks relevant to the missing through holes:
![image](https://user-images.githubusercontent.com/125509/149958073-ad457238-c736-4e57-83dd-34bddad16c17.png)

**Comment by vlkv** [comment]
Hi! I really do not know. Their previewer is not perfect, that is for sure. Anyway, if you have doubts then I recommend you to ask jlcpcb engineers/support about that. Tell them that you need those LED holes, and that previewer doesn't show them.

**Comment by winder** [comment]
I'll talk with support to address these items. Thanks for the help, your comments were more encouraging than you may realize!

**Comment by winder** [comment]
Received the shipment today. Everything seems to be in order. Thanks so much for the help, and for open sourcing your design.

![IMG_20220215_142516.jpg](https://user-images.githubusercontent.com/125509/154134473-4d9c13ad-44df-4295-8bfc-aad7d1df7c8a.jpg)
