### ISSUE TITLE
Is 4.2 released? or is the README up to date that still recommends to wait?

### ISSUE THREAD

**Issue by maxhbr** [vlkv/avalanche#18]

**Comment by vlkv** [comment]
Hi, v4.2 version is OKay, several people already built it, without any issues (as far as I know). Gerbers are here https://github.com/vlkv/avalanche#gerber-files

Can you please show me, where the README recommends to wait? This could be an outdated info, that should be corrected.

**Comment by maxhbr** [comment]
I am very sorry. I accidentally was on https://github.com/vlkv/avalanche/tree/v4.2, where the README is not yet updated. It is all OK on master

**Comment by vlkv** [comment]
No problem, I am glad that everything is good)
